services:
  postgres:
    image: postgres:17-alpine
    container_name: pager-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - pager-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

    container_name: pager-backend

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

    ports:
      - "${BACKEND_PORT}:3000"

    volumes:
      - ./backend:/app

    networks:
      - pager-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile

    container_name: pager-frontend

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - backend

    ports:
      - "${FRONTEND_PORT}:5173"

    volumes:
      - ./frontend:/app

    networks:
      - pager-network

volumes:
  postgres_data:

networks:
  pager-network:
    driver: bridge
