export enum DemandStatusDto {
  NOVA = 'NOVA',
  TRIAGEM = 'TRIAGEM',
  RESPONSAVEL_ATRIBUIDO = 'RESPONSAVEL_ATRIBUIDO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  CONCLUSAO_SINALIZADA = 'CONCLUSAO_SINALIZADA',
  ARQUIVADA = 'ARQUIVADA',
}
